# Generated by Django 5.0.4 on 2024-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incometax', '0002_netsalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
